apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-pod
spec:
  containers:
    - name: ubuntu-container
      image: ubuntu
      envFrom:
        - configMapRef:
            name: configmap-example
      command:
        - "sleep"
        - "1000"