apiVersion: batch/v1
kind: Job
metadata:
  name: math-job
spec:
  ttlSecondsAfterFinished: 500
  completions: 3
  parallelism: 3
  template:
    spec:
      containers:
      - name: ubuntu
        image: ubuntu
        command: ["expr",  "2", "+", "3"]
      restartPolicy: Never
