apiVersion: v1
kind: ResourceQuota
metadata: 
  name: compute-quota
  namespace: production
spec:
  hard:
    pods: "10"
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "1"
    limits.memory: "500m"