apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  namespace: default
  labels:
    app: my-pod
spec:
  containers:
    - name: pod-container
      image: nginx
      command:
        - "sleep"
      args:
        - "50"
