apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  template:
    metadata:
      name: my-pod
      labels:
        type: backend
    spec:
      containers:
        - name: my-container
          image: ubuntu
          command:
            - "sleep"
          args:
            - "1200"
  replicas: 2
  selector:
    matchLabels:
      type: backend