apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30008
  selector:
    app: nginx # pod -> metadata.labels
    type: web-server # pod.yaml -> metadata.labels
    