apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-pod
  labels:
    name: ubuntu-pod
spec:
  containers:
    - name: ubuntu
      image: ubuntu:mantic
      command: ["sleep"]
      args: ["infinity"]
      env:
        - name: USERNAME
          value: guimassoqueto
      securityContext:
        runAsUser: 1000
  restartPolicy: OnFailure
