apiVersion: v1
kind: Pod
metadata:
  name: mypod
  labels:
    name: mypod
spec:
  containers:
  - name: mypod
    image: ubuntu:mantic
    resources:
      requests:
        memory: "128Mi"
        cpu: "500m"
  nodeSelector:
    size: Large # size is the key, Large is the value applied to the Node. See the README
