apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc
spec:
  resources:
    requests:
      storage: 500Mi
  volumeMode: Filesystem
  storage-class-name: aws-ebs
  accessModes:
    - ReadWriteOnce
