apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-pod
spec:
  containers:
  - name: ubuntu-container
    image: ubuntu
    command:
      - "sleep"
      - "2000"
    securityContext:
      runAsUser: 1000
      capabilities:
        add: ["MAC_ADMIN"]