apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-pod
spec:
  securityContext:
    runAsUser: 1000
    capabilities:
      add: ["MAC_ADMIN"]
  containers:
  - name: ubuntu-container
    image: ubuntu
    command:
      - "sleep"
      - "2000"
