apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mantic-linux
  labels:
    app: mantic-linux
    os: linux
spec:
  replicas: 3
  selector:
    matchLabels:
      os: linux
  template:
    metadata:
      labels:
        os: linux
    spec:
      containers:
        - name: ubuntu
          image: ubuntu:mantic
          command: ["sleep"]
          args: ["infinity"]
      restartPolicy: Always