apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    name: myapp-pod
spec:
  containers:
  - name: myapp-pod
    image: simple-webapp
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
    readinessProbe:
      httpGet: 
        path: /api/ready
        port: 8080
        initialDelaySeconds: 10
        periodSeconds: 5
