apiVersion: v1
kind: ResourceQuota
metadata:
  name: resource-quota
  namespace: custom-namespace
spec:
  hard:
    pods: "10"
    request.cpu: "1"
    request.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi