apiVersion: v1
kind: Pod
metadata:
  name: linux
  labels:
    name: linux
spec:
  containers:
  - name: linux
    image: ubuntu:mantic
    resources:
      requests:
        memory: "512Mi"
        cpu: "500m"
      limits:
        memory: "1Gi"
        cpu: "1"
